version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "cd app && npm run dev"
    ports:
      - 3000:3000